#!/usr/bin/env bash

dotfiles="https://github.com/skykosiner/.dotfiles"

installpkg() {
	pacman --noconfirm --needed -S "$1"
}

installpkgyay() {
	yay --noconfirm --needed -S "$1"
}

installSuckless() {
    git clone "https://github.com/skykosiner/$1" "/home/$user/.local/src/$1"
    pushd "/home/$user/.local/src/$1"
    sudo make install
    popd
}

read -p "Please enter your username used to setup the system: " user

# Update system before anything
printf "Updating system..."
pcaman -Syyu

# Install some base packages needed to do anything
installpkg git
installpkg base-devel

# Run sudo commands without the password
printf "Sudo can be run without sudo password"
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers

# Make pacman colorful, concurrent downloads and Pacman eye-candy.
printf "Making pacman look nice"
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

# Use all cores when compling things with make
printf "Using all cores to compile things"
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf

# Installing yay (aur helper)
printf "Installing aur helper yay"
git clone https://aur.archlinux.org/yay.git
cd ./yay
makepkg -si
cd ..
rm -rf ./yay

# Make sure .*-git AUR packages get updated automatically.
yay -Y --save --devel

# Install programs now
printf "Installing programs from pacman"
while read p; do
    installpkg "$p"
done <pacman-install-list

printf "Installing programs from aur"
while read p; do
    installpkgyay "$p"
done <yay-install-list

printf "Installing qbt cli"
git clone https://github.com/ludviglundgren/qbittorrent-cli
cd ./qbittorrent-cli
go build -o /usr/bin/qbt cmd/qbt/main.go
cd ..
rm -rf ./qbittorrent-cli

# Install dmenu, st, dwm, and dwmblocks
printf "Installing suckless software"
installSuckless "dmenu"
installSuckless "st"
installSuckless "dwm"
installSuckless "dwmblocks"

# Get sound setup
# Dotfiles
# Ask about setting up Nvidia drivers, then ask to use optimus manger or not
