#!/usr/bin/env bash

installpkg() {
	pacman --noconfirm --needed -S "$1"
}

installpkgyay() {
	yay --noconfirm --needed -S "$1"
}

installSuckless() {
    git clone "https://github.com/skykosiner/$1" "/home/$user/.local/src/$1"
    pushd "/home/$user/.local/src/$1"
    make install
    popd
}

read -p "Please enter your username used to setup the system: " user

# Update system before anything
printf "Updating system..."
pcaman -Syyu

# Install some base packages needed to do anything
installpkg git
installpkg base-devel

# Run sudo commands without the password
printf "Sudo can be run without sudo password"
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers

# Make pacman colorful, concurrent downloads and Pacman eye-candy.
printf "Making pacman look nice"
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

# Use all cores when compling things with make
printf "Using all cores to compile things"
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf

# Installing yay (aur helper)
printf "Installing aur helper yay"
git clone https://aur.archlinux.org/yay.git
cd ./yay
sudo -u "$user" makepkg -si
cd ..
rm -rf ./yay

# Make sure .*-git AUR packages get updated automatically.
yay -Y --save --devel

# Install programs now
printf "Installing programs from pacman"
while read p; do
    installpkg "$p"
done <pacman-install-list

printf "Installing programs from aur"
while read p; do
    installpkgyay "$p"
done <yay-install-list

printf "Installing qbt cli"
git clone https://github.com/ludviglundgren/qbittorrent-cli
cd ./qbittorrent-cli
go build -o /usr/bin/qbt cmd/qbt/main.go
cd ..
rm -rf ./qbittorrent-cli

printf "Installing neovim"
git clone https://github.com/neovim/neovim "/home/$user/.local/src/neovim"
pushd "/home/$user/.local/src/neovim"
make
make install
popd

# Install dmenu, st, dwm, and dwmblocks
printf "Installing suckless software"
installSuckless "dmenu"
installSuckless "st"
installSuckless "dwm"
installSuckless "dwmblocks"

# DWM link for X11
touch /usr/share/xsessions/dwm.desktop
echo "[Desktop Entry]\nEncoding=UTF-8\nName=dwm\nComment=Dynamic windo manger\nExec=dwm\nIcon=dwm\nType=XSession" >> /usr/share/xsessions/dwm.desktop

# Dotfiles
printf "Setting up dotfiles"
git clone https://github.com/skykosiner/.dotfiles "/home/$user/.dotfiles/"
pushd "/home/$user/.dotfiles"
export DOTFILES=/home/$user/.dotfiles
export STOW_FOLDERS="bin,nvim,tmux,zsh,shell,dunst,fonts,vim,qutebrowser,zathula,lf,emacs,picom,newsboat"
./install
popd

printf "Setting up packer for neovim"
# Instaling packer it self
sudo -u "$user" git clone --depth 1 https://github.com/wbthomason/packer.nvim\
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# TODO: Install all plugins with packer

# Ask about setting up Nvidia drivers, then ask to use optimus manger or not
printf "Would you like to setup nvidia drivers?"
read "[y/n] " ans

# TODO: Setup nvidia drivers
if [[ $ans == "y" ]]; then
fi

# Install and setup all the fun X11 stuff
installpkg xorg
installpkg xorg-xinit

# Install and setup sddm
installpkg sddm

# Get sound setup
